import { playwright } from '@vitest/browser-playwright';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    projects: [
      {
        // 沿用现状：hooks + utils + Phase A/B 组件，jsdom 环境，零返工
        test: {
          name: 'unit',
          environment: 'jsdom',
          globals: true,
          setupFiles: ['./test/setup.ts'],
          include: [
            'test/components/**/*.test.ts',
            'test/components/**/*.test.tsx',
            'test/hooks/**/*.test.ts',
            'test/hooks/**/*.test.tsx',
            'test/utils/**/*.test.ts',
            'test/utils/**/*.test.tsx',
          ],
          exclude: ['**/*.browser.test.ts', '**/*.browser.test.tsx'],
          coverage: {
            provider: 'v8',
            include: [
              'src/hooks/use*.ts',
              'src/hooks/use*.tsx',
              'src/hooks/style/useSplitter.ts',
              'src/utils/AudioPlayer.ts',
              'src/utils/base64.ts',
              'src/utils/color.ts',
              'src/utils/crypto.ts',
              'src/utils/math.ts',
              'src/utils/stream.ts',
              'src/utils/string.ts',
              'src/utils/StreamDownloader/index.ts',
              'src/utils/StreamDownloader/StreamDownloadError.ts',
              'src/components/index.tsx',
              'src/components/BreakLines/index.tsx',
              'src/components/Loading/index.tsx',
              'src/components/Loading/style/index.ts',
              'src/components/Animation/Pulse/index.tsx',
              'src/components/Animation/Pulse/style/index.ts',
              'src/components/Iconfont/index.tsx',
              'src/components/Iconfont/createIconfont.tsx',
              'src/components/FormItemControl/index.tsx',
              'src/components/EllipsisTypography/EllipsisParagraph.tsx',
              'src/components/EllipsisTypography/EllipsisText.tsx',
              'src/components/EllipsisTypography/EllipsisTitle.tsx',
              'src/components/EllipsisTypography/EllipsisLink.tsx',
              'src/components/EllipsisTypography/withEllipsisTypography.tsx',
              'src/components/DeleteConfirmAction/index.tsx',
              'src/components/DeleteConfirmAction/withDeleteConfirmAction.tsx',
              'src/components/ConfigProvider/index.tsx',
              'src/components/ConfigProvider/context.tsx',
              'src/components/ConfigProvider/style/index.ts',
              'src/components/OverflowTags/index.tsx',
              'src/components/OverflowTags/style/index.ts',
              'src/components/ColumnSetting/index.tsx',
              'src/components/ColumnSetting/style/index.ts',
              'src/components/ContextMenu/index.tsx',
              'src/components/ContextMenu/style/index.ts',
              'src/components/Lexical/index.ts',
              'src/components/Lexical/helpers/index.ts',
              'src/components/Lexical/nodes/base.ts',
              'src/components/Lexical/nodes/DivNode.tsx',
              'src/components/Lexical/nodes/ExtendTextNode.tsx',
              'src/components/Lexical/nodes/CloseIcon.tsx',
            ],
            exclude: ['src/hooks/useUserMedia.tsx'],
            reporter: ['text', 'html', 'json-summary', 'clover', 'json', 'lcov'],
            thresholds: {
              statements: 100,
              branches: 100,
              functions: 100,
              lines: 100,
            },
          },
        },
      },
      {
        // 新增：Phase C 三个高成本组件，真实 Chromium 环境，不 mock Ant Design 内部
        test: {
          name: 'browser',
          browser: {
            enabled: true,
            provider: playwright(),
            headless: true,
            instances: [{ browser: 'chromium' }],
          },
          globals: true,
          include: [
            'test/browser/**/*.test.ts',
            'test/browser/**/*.test.tsx',
            'test/utils/*.browser.test.ts',
            'test/utils/*.browser.test.tsx',
          ],
          coverage: {
            provider: 'v8',
            include: [
              'src/components/ConfirmAction/index.tsx',
              'src/components/ConfirmAction/withConfirmAction.tsx',
              'src/components/ModalAction/index.tsx',
              'src/components/VirtualTextViewer/index.tsx',
            ],
            exclude: ['src/components/VirtualTextViewer/types.ts'],
            reporter: ['text', 'html', 'json-summary', 'clover', 'json', 'lcov'],
            thresholds: {
              statements: 100,
              branches: 100,
              functions: 100,
              lines: 100,
            },
          },
        },
      },
    ],
  },
});
