name: Reusable Tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: Specific Node.js version for a single test run.
        default: ${{vars.DEFAULT_NODE_VERSION}}
      use-matrix:
        required: false
        type: boolean
        description: Whether to run tests with the configured Node.js matrix.
        default: false

jobs:
  test-matrix:
    if: ${{ inputs.use-matrix == true }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 23.x, 24.x, 25.x]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Playwright dependencies
        run: npx playwright install-deps webkit

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  test-single:
    if: ${{ inputs.use-matrix == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Playwright dependencies
        run: npx playwright install-deps webkit

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
